export const categoryListDetails = [
  {
    categoryName: 'Best selling products',
    categorySubTopicList: [
      {
        pName: 'Blueberries',
        id: 107,
      },
      {
        pName: 'Pomegranate',
        id: 150,
      },
      {
        pName: 'chicken breast',
        id: 112,
      },
      {
        pName: 'tuna',
        id: 119,
      },
    ],
    products: [
      {
        pName: 'Blueberries',
        pDesc: 'exotic & fresh',
        pWeight: '125g',
        price: 149,
        rating: 4,
        discount: '26%',
        img: 'images/products/fruits&vegetables/blueberries/blueberries.webp',
        id: 107,
        quantity: 1,
        addedToCart: false,
        addedToWishlist: false,
      },
      {
        pName: 'Pomegranate',
        pDesc: 'local & fresh',
        pWeight: '440g 500gm',
        price: 95,
        rating: 4,
        discount: '26%',
        img: 'images/products/fruits&vegetables/pomegranate/pomogranate-1.webp',
        id: 150,
        quantity: 1,
        addedToCart: false,
        addedToWishlist: false,
      },
      {
        pName: 'Chicken Breast-Boneless',
        pDesc: 'Boneless | Fillet',
        pWeight: '450g',
        price: 229,
        rating: 4,
        discount: '26%',
        img: 'images/products/meat&fish/chicken-breast/chicken_breast-1.webp',
        id: 112,
        quantity: 1,
        addedToCart: false,
        addedToWishlist: false,
      },
      {
        pName: 'Yellowfin Tuna',
        pDesc: 'Seawater fish',
        pWeight: '300g',
        rating: 4,
        price: 229,
        img: 'images/products/meat&fish/tuna/tuna.webp',
        id: 119,
        quantity: 1,
        addedToCart: false,
        addedToWishlist: false,
      },
    ],
  },
  {
    categoryName: 'Best from Farmers',
    categorySubTopicList: [
      {
        pName: 'Carrots',
        id: 108,
      },
      {
        pName: 'Brown eggs',
        id: 101,
      },
      {
        pName: 'Milk',
        id: 104,
      },
      {
        pName: 'Mutton',
        id: 116,
      },
    ],
    products: [
      {
        pName: 'Carrots',
        pDesc: 'local & fresh',
        pWeight: '250g',
        price: 14.49,
        rating: 4,
        img: 'images/products/fruits&vegetables/carrots/carrot-1.webp',
        id: 108,
        quantity: 1,
        addedToCart: false,
        addedToWishlist: false,
        category: 'fruits&vegetables',
      },
      {
        pName: 'Brown eggs',
        pDesc: 'local & fresh',
        pWeight: '30 peices',
        price: 235,
        rating: 4,
        discount: '26%',
        img: 'images/products/bakery/brown-eggs/brownEgg-1.png',
        id: 101,
        quantity: 1,
        addedToCart: false,
        addedToWishlist: false,
      },
      {
        pName: 'Milk',
        pDesc: '6x1 L Multipack ',
        pWeight: '450g',
        price: 379,
        rating: 4,
        img: 'images/products/bakery/milk/milk-1.webp',
        id: 104,
        quantity: 1,
        addedToCart: false,
        addedToWishlist: false,
      },
      {
        pName: 'Mutton',
        pDesc: 'barn raised',
        pWeight: '500g',
        price: 559,
        discount: '26%',
        rating: 4,
        img: 'images/products/meat&fish/mutton-lean-curry-cut/lean_goat_curry-cut-1.png',
        id: 116,
        quantity: 1,
        addedToCart: false,
        addedToWishlist: false,
      },
    ],
  },
];
