export const categoryListProductDetails = [
  {
    bakery: [
      {
        pName: 'bread',
        pDesc: 'freshly baked',
        pWeight: '200g',
        weights: ['200gm', '400gm'],
        price: 25,
        img: 'images/products/bakery/bread/bread1.webp',
        rating: 4,
        discount: '00%',
        id: 100,
        quantity: 1,
        category: 'bakery',
      },
      {
        pName: 'brown eggs',
        pDesc: 'fresh',
        pWeight: '12 units',
        weights: ['12 units', '24 units'],
        price: 140,
        img: 'images/products/bakery/brown-eggs/brownEgg-1.png',
        rating: 5,
        discount: '26%',
        id: 101,
        quantity: 1,
        category: 'bakery',
      },
      {
        pName: 'cheese slices',
        pDesc: 'fresh',
        pWeight: '12 units',
        weights: ['12 units', '24 units'],
        price: 140,
        img: 'images/products/bakery/cheese/cheese-1.webp',
        rating: 3,
        discount: '26%',
        id: 102,
        quantity: 1,
      },
      {
        pName: 'curd',
        pDesc: 'fresh',
        pWeight: '250 gms',
        weights: ['250 gms', '500 gms'],
        price: 40,
        img: 'images/products/bakery/curd/curd-1.webp',
        rating: 2,
        discount: '26%',
        id: 103,
        quantity: 1,
      },
      {
        pName: 'white eggs',
        pDesc: 'fresh',
        pWeight: '12 units',
        weights: ['12 units', '24 units'],
        price: 40,
        img: 'images/products/bakery/egg/egg-1.webp',
        rating: 4,
        discount: '00%',
        quantity: 1,
        id: 190,
      },
      {
        pName: 'milk',
        pDesc: 'fresh',
        pWeight: '1l',
        weights: ['1lx1 ', '1lx3'],
        price: 40,
        img: 'images/products/bakery/milk/milk-1.webp',
        rating: 5,
        discount: '16%',
        id: 104,
        quantity: 1,
      },
      {
        pName: 'quail eggs',
        pDesc: 'fresh',
        pWeight: '12 units',
        weights: ['12 units', '24 units'],
        price: 140,
        img: 'images/products/bakery/quailEgg/QuailEgg-1.jpeg',
        rating: 4,
        discount: '12%',
        id: 105,
        quantity: 1,
      },
      {
        pName: 'soymilk',
        pDesc: 'fresh',
        pWeight: '1l',
        weights: ['1lx1 ', '1lx3'],
        price: 40,
        img: 'images/products/bakery/soymilk/soy-milk-1.webp',
        rating: 2,
        discount: '00%',
        id: 106,
        quantity: 1,
      },
    ],
    'fruits&vegetables': [
      {
        pName: 'blueberries',
        pDesc: 'exotic & fresh',
        pWeight: '125g',
        price: 149,
        img: 'images/products/fruits&vegetables/blueberries/blueberries.webp',
        rating: 3,
        discount: '00%',
        id: 107,
        quantity: 1,
      },

      {
        pName: 'carrots',
        pDesc: 'local & fresh',
        pWeight: '250g',
        price: 14.49,
        img: 'images/products/fruits&vegetables/carrots/carrot-1.webp',
        rating: 4,
        discount: '00%',
        id: 108,
        quantity: 1,
      },
      {
        pName: 'Mangoes',
        pDesc: 'local & fresh',
        pWeight: '1kg',
        price: 14.49,
        img: 'images/products/fruits&vegetables/mango/mango-1.webp',
        rating: 5,
        discount: '00%',
        id: 109,
        quantity: 1,
      },
      {
        pName: 'pomegranate',
        pDesc: 'local & fresh',
        pWeight: '1kg',
        price: 14.49,
        img: 'images/products/fruits&vegetables/pomegranate/pomogranate-1.webp',
        rating: 5,
        discount: '6%',
        id: 150,
        quantity: 1,
      },
      {
        pName: 'sweet Potato',
        pDesc: 'local & fresh',
        pWeight: '1kg',
        price: 14.49,
        img: 'images/products/fruits&vegetables/sweet-potato/sweet_potato.webp',
        rating: 3,
        discount: '00%',
        id: 110,
        quantity: 1,
      },
      {
        pName: 'watermelon',
        pDesc: 'local & fresh',
        pWeight: '1kg',
        price: 14.49,
        img: 'images/products/fruits&vegetables/watermelon/watermelon-1.webp',
        rating: 4,
        discount: '00%',
        id: 111,
        quantity: 1,
      },
    ],
    'meat&fish': [
      {
        pName: 'chicken Breast-Boneless',
        pDesc: 'Boneless | Fillet',
        pWeight: '450g',
        price: 229,
        img: 'images/products/meat&fish/chicken-breast/chicken_breast-1.webp',
        rating: 5,
        discount: '16%',
        id: 112,
        quantity: 1,
      },
      {
        pName: 'chicken Curry-Cut',
        pDesc: 'Boneless | Fillet',
        pWeight: '450g',
        price: 229,
        img: 'images/products/meat&fish/chicken-curry-cut/chicken_curry_cut-1.webp',
        rating: 4,
        discount: '25%',
        id: 113,
        quantity: 1,
      },
      {
        pName: 'chicken Drumstick',
        pDesc: 'fresh',
        pWeight: '450g',
        price: 229,
        img: 'images/products/meat&fish/chicken-drumstick/chicken_drumstick-1.webp',
        rating: 4,
        discount: '24%',
        id: 114,
        quantity: 1,
      },
      {
        pName: 'Mutton boneless',
        pDesc: 'fresh',
        pWeight: '450g',
        price: 429,
        img: 'images/products/meat&fish/mutton-boneless/mutton-boneless-1.jpeg',
        rating: 5,
        discount: '00%',
        id: 115,
        quantity: 1,
      },
      {
        pName: 'mutton lean goat curry-cut',
        pDesc: 'fresh',
        pWeight: '450g',
        price: 529,
        img: 'images/products/meat&fish/mutton-lean-curry-cut/lean_goat_curry-cut-1.png',
        rating: 5,
        discount: '00%',
        id: 116,
        quantity: 1,
      },
      {
        pName: 'prawns',
        pDesc: 'fresh',
        pWeight: '450g',
        price: 329,
        img: 'images/products/meat&fish/prawns/prawns-1.webp',
        rating: 1,
        discount: '00%',
        id: 117,
        quantity: 1,
      },
      {
        pName: 'salmon',
        pDesc: 'fresh',
        pWeight: '250g',
        price: 429,
        img: 'images/products/meat&fish/salmon/salmon-1.webp',
        rating: 4,
        discount: '00%',
        id: 118,
        quantity: 1,
      },
      {
        pName: 'yellowfin Tuna',
        pDesc: 'Seawater fish',
        pWeight: '300g',
        rating: 3,
        discount: '00%',
        price: 229,
        img: 'images/products/meat&fish/tuna/tuna.webp',
        id: 119,
        quantity: 1,
      },
    ],
    drinks: [
      {
        pName: 'beer',
        pDesc: 'alag taste',
        pWeight: 'Budweiser 650ML',
        price: 210,
        img: 'images/products/drinks/beer/beer-1.webp',
        rating: 1,
        discount: '00%',
        id: 120,
        quantity: 1,
      },
      {
        pName: 'gluconD',
        pDesc: 'tasty',
        pWeight: '100gm',
        price: 50,
        img: 'images/products/drinks/glucond/glucond-1.webp',
        rating: 2,
        discount: '00%',
        id: 121,
        quantity: 1,
      },
      {
        pName: 'monster',
        pDesc: 'tasty',
        pWeight: '250ml',
        price: 190,
        img: 'images/products/drinks/monster/monster-1.webp',
        rating: 3,
        discount: '00%',
        id: 122,
        quantity: 1,
      },
      {
        pName: 'protienX',
        pDesc: 'healthy',
        pWeight: '500gm',
        price: 290,
        img: 'images/products/drinks/protien/protienX1.webp',
        rating: 4,
        discount: '00%',
        id: 123,
        quantity: 1,
      },
    ],
  },
];
